import Head from "next/head";

const HeadElement = () => {
  return (
    <Head>
      <title>Bandex Science Academy - Birnin Kebbi</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.jpg" />
    </Head>
  );
};

export default HeadElement;
